{% set name = "graphene-django" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ebf61a8b13ff6d7433c95b2efdaf723b1ee6bf8e74a34d89a378f1151c104ff

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - django >=1.11
    - graphene >=2.1.7,<3
    - graphql-core >=2.1.0,<3
    - promise >=2.1
    - python
    - singledispatch >=3.4.0.3
    - six >=1.10.0
    - unidecode >=1.1.1,<2

about:
  home: https://github.com/graphql-python/graphene-django
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Graphene Django integration
  description: Graphene-Django is built on top of Graphene. Graphene-Django provides some additional abstractions that make it easy to add GraphQL functionality to your Django project.
  doc_url: https://docs.graphene-python.org/projects/django/en/latest/
  dev_url: https://github.com/graphql-python/graphene-django

extra:
  recipe-maintainers:
    - KingDarBoja
